### ISSUE TITLE
Randomizer doesn't work with NTSC version (Windows version)

### ISSUE THREAD

**Issue by Hdot12TTV** [markisha64/dmw3-randomizer#2]
The bar stops at around 75% when using an NTSC file and the cmd window displays:
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src\rand.rs:264:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by markisha64** [comment]
fixed with [#f3e7cebf3a](https://github.com/markisha64/dmw3-randomizer/commit/f3e7cebf3ac0831be61238417387af53021305f8)
