### ISSUE TITLE
Galacticmon Runaway breaks the game

### ISSUE THREAD

**Issue by Hdot12TTV** [markisha64/dmw3-randomizer#3]
Phase 1 Galacticmon ran away and the game can not handle that. It places you out of bounds on the final Gunslinger screen when it should play the credits instead because it is an instant win in all other cases too.

**Comment by markisha64** [comment]
Added `Keep Galacticmon` checkbox in [db2185a](https://github.com/markisha64/dmw3-randomizer/commit/db2185a2de3846210dd8a828eb39a74ab0d83e05)
