### ISSUE TITLE
Galacticmon Phase 3 secondary attacks don't work

### ISSUE THREAD

**Issue by Hdot12TTV** [markisha64/dmw3-randomizer#4]
If Phase 3 Galacticmon is a Digimon with no Technique then it will never perform the counter or the laser attack. Instead no animations happen and it will say that your Digimon evaded the attack. It never actually hits

**Comment by markisha64** [comment]
Happens because Digimon in phase 3 doesn't have moves.

Added `Keep Galacticmon` checkbox in [db2185a](https://github.com/markisha64/dmw3-randomizer/commit/db2185a2de3846210dd8a828eb39a74ab0d83e05)
