### ISSUE TITLE
Dark Power S invsibile in inventory

### ISSUE THREAD

**Issue by Hdot12TTV** [markisha64/dmw3-randomizer#5]
Dropped Dark Power S on a certain seed (729567010427) but it didn't show up in the inventory. When buyable in a shop it showed that I had 1 copy of it though.

**Comment by markisha64** [comment]
Issue caused by overwriting `No Item`'s shop data (which is in fact end of some other data array)
Fixed with [9a1b676](https://github.com/markisha64/dmw3-randomizer/commit/9a1b67658b73789ee3ca76c32854cfb0abe21d38)
